### ISSUE TITLE
Thin-space comma gets detached from its escape character

### ISSUE THREAD

**Issue by rbeezer** [davidfarmer/LaTeXtoLaTeX#12]
Source (Judson's private solutions):

```xml
Noting that <m>\omega^3 = 1</m> and <m> (1 - \omega)^3 = -3(\omega - \omega^2) = -3 \sqrt{3} \, </m>,  we can further conclude that
```

appears to become, via `ltol.py xml_pp`,

```xml
Noting that <m>\omega^3 = 1</m> and
<m> (1 - \omega)^3 = -3(\omega - \omega^2) = -3 \sqrt{3} \</m>,, we can further conclude that
```

Then the conversion to LaTeX produces `\\),,` which does not compile because the final `\)` is not found, due to the `\\` being interpreted first.

In the middle of convoluted rearrangements of AATA source, but I'm pretty sure I've got this described accurately.

(Yes, the source is bad, but maybe swapping the trailing punctuation out is a bit over-aggressive?)

**Comment by davidfarmer** [comment]
The solution which makes sense to me is to first delete any `\,` before a closing "m" tag,
since it shouldn't be there.  Then run the prettyprinter.

I'll do that tomorrow unless you have a better suggestion.

I can tell you what lines to comment out if you don't want the commas moved to after the m tag
(although I don't know why you would want that to be left wrong or left to be fixed by hand later).

**Comment by rbeezer** [comment]
Solution sounds good to me, nothing obviously better to suggest.  Only one instance, which I will just fix by hand in the final resut of the conversion.  (So, no rush.)

Just generated the AATA solutions manual, with no other problems, so maybe that is the only hiccup?  Stay tuned.

**Comment by davidfarmer** [comment]
Fixed in most recent commit.
